services:
  web:
    container_name: cloudflare-failover500
    build:
      args:
        - FLASK_ENV=dev
      context: .
    volumes:
      - ./src:/src
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - TEMPLATE_AUTO_RELOAD=True
      - PYTHONUNBUFFERED=1
    ports:
      - "8010:8000"
